feat(TPG>=4.78)!: add cloud storage subscription support
terraform-google-modules/terraform-google-pubsub pull request #145
Opened 2023-08-16 21:30 UTC by lahuang4

I tried running tests by changing `skip: true` to `skip: false` in `examples/bigquery/test.yaml`, but I'm getting errors along the lines of:

```
Error: No value for required variable

on variables.tf line 17:
17: variable "project_id" {

The root module input variable "project_id" is not set, and has no default
value. Use a -var or -var-file command line argument to provide a value for
this variable.}
```

Not sure how to get this to run correctly, would appreciate any tips. But it seems like all the tests are in this state, not just my newly-added cloud_storage test.

2023-08-17 15:07 UTC, apeabody commented
/gcbrun

2023-08-17 15:18 UTC, apeabody commented
Hi @bharathkkb Do you happen to recall why the test referenced above was skipped? https://github.com/terraform-google-modules/terraform-google-pubsub/blob/master/examples/kms/test.yaml#L20

2023-08-23 21:11 UTC, tcoyze commented
Hi @lahuang4, you should be able to pass that error by running (for example):

`terraform plan -var "project_id=<your google cloud project id>"`

Thank you for contributing! 👍

2023-10-23 16:27 UTC, lahuang4 commented
Oops, I've let this linger too long. Can't seem to figure out how to remove the Stale label; maybe commenting will do the trick to keep the PR alive.

2023-10-23 19:34 UTC, lahuang4 commented
OK, I couldn't figure out how to pass the variables to the integration tests in the end (I tried tcoyze@'s suggestion but maybe I am triggering the tests incorrectly because the vars were not persisting to the test run), but I've run the new Cloud Storage example myself by running `terraform apply` and seeing the correct result!

I've left the newly added test.yaml annotated as `skip: true` for now.

While running the example I decided that it may be useful to have the bucket name passed in as a variable -- due to the global Cloud Storage bucket namespace it's likely that any placeholder we put in the example is going to be taken already, and the same bucket name is used both in the google_storage_bucket object and the cloud_storage_subscriptions object.

This is ready for review now!

2023-10-23 19:41 UTC, apeabody commented
/gcbrun

2023-10-23 19:43 UTC, apeabody commented
Hi @lahuang4 - From the lint

```
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/examples/cloud_storage/README.md /tmp/tmp.pwvq4L4jPc/generate_docs/workspace/examples/cloud_storage/README.md
10d9
< | project\_id | The project ID to manage the Pub/Sub resources | `string` | n/a | yes |
11a11
> | project\_id | The project ID to manage the Pub/Sub resources | `string` | n/a | yes |
17d16
< | project\_id | The project ID |
18a18
> | project\_id | The project ID |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
```

2023-10-23 19:56 UTC, apeabody requested changes
Thanks for the contribution @lahuang4! - A few notes below for now :)

2023-10-23 19:56 UTC, apeabody commented on test/setup/versions.tf
> +      version = "~> 4.78"
```suggestion
      version = ">= 4.78"
```

2023-10-23 19:56 UTC, apeabody commented on test/setup/versions.tf
> +      version = "~> 4.78"
We want to allow to run on TPG 5

2023-10-23 19:56 UTC, apeabody commented on examples/cloud_storage/versions.tf
> +/**
Let's drop this file, we no longer require `version.tf` for examples and we don't want to restrict TPG 5.

2023-10-23 19:56 UTC, apeabody commented on examples/cloud_storage/test.yaml
> +  skip: true
Let's figure out why this test doesn't work.

2023-10-23 20:12 UTC, apeabody commented
/gcbrun

2023-10-23 20:49 UTC, apeabody commented
/gcbrun

2023-10-23 20:52 UTC, apeabody commented
/gcbrun

2023-10-23 21:08 UTC, apeabody commented
/gcbrun

2023-10-23 21:25 UTC, apeabody commented
/gcbrun

2023-10-23 21:26 UTC, apeabody commented on examples/bigquery/test.yaml
> +  skip: true
Guessing this test was failing due to re-use of the subscription name in the cloud_storage example.

2023-10-23 21:48 UTC, apeabody commented
/gcbrun

2023-10-23 22:07 UTC, apeabody commented
/gcbrun

2023-10-23 22:47 UTC, apeabody approved these changes

2023-10-25 16:40 UTC, merged